import React, { Component } from "react";
        import OneDestination from "../../../common/OneDestination/OneDestination";

        export default class ManangTilichoTrek extends Component {
            componentDidMount() {
    window.scrollTo(0, 0);
  }
          render() {
            return (
              <div>
                <OneDestination
                  title="Manang Tilicho Trek – 13 Days"
                  url="https://www.caravanoutdoors.com/wp-content/uploads/2017/06/Tilicho_Lake.jpg"
                  para1="Manang is a city located inside the Manang district of mid-western Nepal. It lies to the north of Annapurna mountain range and around Marshyangdi River. It also forms a part of the greater Annapurna circuit trail.Gangapurna, and Annapurna I,II and III peaks are clearly visible from Manang."
                  para2=" The trek begins from Besisahar, and advances through the same trail leading towards Annapurna circuit. After reaching Manang, you will get to do a hike around Tilicho Lake, the highest lake in the world. After a short hike, you will descend down the same way until Hungde"
                  para3=" A short flight from Hungde will take you back to Kathmandu.Manange (Manangi) account for the indigenous tribe of the region. They depend mostly on trading, yak caravans and tourism to earn money. Tilicho Lake is the major attraction of the trek. It is a glacial lake with no trace of any aquatic life."
                  itineraryes={[[["Arrival in Kathmandu"],["\nAt your arrival in Kathmandu, a member of our team will greet and receive you at the airport. You will be transferred to your hotel. Our representative will brief on your arrival about the trip. The rest of the day is yours. The evening we be spent enjoying complimentary local dinner one of the finest local diner with cultural program"]],[["Drive from Besi Sahar – Bhulbhule"],["\nYou will drive along the Kathmandu-Pokhara Highway to Besi Sahar after 6-7 hours of long drive, and make a stop further towards Bhubhule. You can spend the rest of the day here."]],[["Drive to Jagat"],["\nFrom Bhulbhule, you will start the trek. The first stop will be made at Jagat, a small Gurung village. The first day attracts a shorter hike to help you get used to walking."]],[["Trek to Bagarchap"],["\nThe trek passes along the Marsyangdi River. An hour walk from Dharapani would brings you to Bagarchhap Village."]],[["Trek to Chame"],["\nThe day starts with an easy hike to Danaque and then the trail goes along the steep uphill climb to Timang Village. Here you can enjoy the magnificent views of Manaslu Range, Lamjung & Annapurna II. The day ends at Chame village."]],[["Trek to Pisang"],["\nThe trail advances through the lush pine forest with few uneven terrains to cross. Pisang is one of the major stops during the trek.  The village offers the view of Pisang peak and Mt. Chulu, two short peaks. You can spend the rest of the day visiting Upper Pisang village, which is popular for its Tibetan style houses and monasteries."]],[["Trek to Manang"],["\nThe trails ascend towards Manag valley. En route, you can see beautiful Manang valley, along with the view of Humde village, towering peaks of Gangapurna, Annapurna II & III, Tilicho and many others. You will reach Manang Village via Bagra."]],[["Trek to Tilicho Base Camp"],["\nTilicho Base Camp is located around 4,200 meters. It may take a while to reach here, as the ascent will be sharp and difficult. You can spend the evening relaxing."]],[["Tilicho Lake Hike"],["\nAfter breakfast, you will start hiking towards Tilicho Lake. Tilicho Lake is situated at the highest elevation in the world. At around 5,100 meters above the sea level, the lake offers spectacular view of the surrounding mountains. You can come back to Tilicho Base Camp for the overnight stay."]],[["Trek to Manang"],["\nThe trek will descend towards Manang. You  will come down the same way you went up. You can try cathcing up the view of Gangapurna, Annapurna and Tilicho for the last time."]],[["Trek to Hungde"],["\nFrom Manang, you will come down towards Hungde, a small town. You can spend the night here and prepare to fly out to Kathmandu the day after."]],[["Fly to Kathmandu"],["\nTake a short flight back to Kathmandu. You will be transferred to your hotel."]],[["Depart from Kathmandu"],["\nYou will be transferred to the Airport to catch your flight back home."]]]}
                  includedListData={["Arrival airport pick and drop.","Dinner in one of the finest diners in Kathmandu before and after the trek.","2 Nights at ★★★★★ hotel in Kathmandu.","Entire land commute during the trip.","Domestic flight from Hungde to Kathmandu","Standard Tea-house/ Lodge during the trek.","Entire (Breakfast, Lunch, Dinner) Meals during the trek.","A la Carte meal options during the trek.","1 Certified Guide (Licensed & First Aid Trained)/1 Porter (For two)","Guide’s insurance, meals and other costs","TIMS Card/ National Park entry fee/Other Permits","All the Gov. and Local taxes as per applicable","Trekking Map and Group medical kit box (Diamox and First Aid Medicine)","Trip Completion Certificate","Arrangement of Rescue/Medical Helicopter service; covered by your Insurance agency."]}
                  excludedListData={["Visa & Processing Fee","International flight fares","Meals other than during the trek and before/after complimentary dinner","Mineral water and refreshments during the trek","Travel insurance (Cover Helicopter evacuation and Trip Cancellation charges)","Guide/Porter Tipping"]}
                  departureDates={[]}
                  promoOffer={["Manang Tilicho Trek – 13 Days","$ 1,599USD"]}
                  details={["13 days","5,100 meters (16,732 ft)","Full board on trek","Private Vehicle, Tourist Bus","Throughout the year","Moderate","1-10 per Group"]}
                />
              </div>
            );
          }
        }
        